apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: %NODE_IP%:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --allow-privileged=true
    - --apiserver-count=1
    - --audit-log-maxage=30
    - --audit-log-maxbackup=3
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/audit.log
    - --authorization-mode=Node,RBAC
    - --advertise-address=%NODE_IP%
    - --client-ca-file=/etc/kubernetes/certs/ca.pem
    - --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/certs/ca.pem
    - --etcd-certfile=/etc/kubernetes/certs/kubernetes.pem
    - --etcd-keyfile=/etc/kubernetes/certs/kubernetes-key.pem
    - --etcd-servers=https://127.0.0.1:2379
    - --event-ttl=1h
    - --insecure-port=0
    - --encryption-provider-config=/etc/kubernetes/encryption-config.yaml
    - --kubelet-certificate-authority=/etc/kubernetes/certs/ca.pem
    - --kubelet-client-certificate=/etc/kubernetes/certs/kubernetes.pem
    - --kubelet-client-key=/etc/kubernetes/certs/kubernetes-key.pem
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-https=true
    # - --proxy-client-cert-file=/etc/kubernetes/certs/front-proxy-client.crt
    # - --proxy-client-key-file=/etc/kubernetes/certs/front-proxy-client.key
    # - --requestheader-allowed-names=front-proxy-client
    # - --requestheader-client-ca-file=/etc/kubernetes/certs/front-proxy-ca.crt
    # - --requestheader-extra-headers-prefix=X-Remote-Extra-
    # - --requestheader-group-headers=X-Remote-Group
    # - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/certs/service-account.pem
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-node-port-range=30000-32767
    - --tls-cert-file=/etc/kubernetes/certs/kubernetes.pem
    - --tls-private-key-file=/etc/kubernetes/certs/kubernetes-key.pem
    - --v=2
    image: k8s.gcr.io/kube-apiserver:v1.18.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: %NODE_IP%
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}
